name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v4
    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: set up Go module cache
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: install golint
      run: go install golang.org/x/lint/golint@latest
    - name: run tests
      run: make test
